runtime: go122

# This is needed to use GAE Mail API via `mailer` module.
# app_engine_apis: true

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
#
# This configuration is only used for developer testing. The
# configuration used for development and production instances is
# contained in the infradata/gae repo. Refer to LUCI GAE Automatic
# Deployment for more (go/luci/how_to_deploy.md) (Googlers only).
luci_gae_vars:
  luci-tree-status-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    OAUTH_CLIENT_ID: 713057630411-eqah8ap1ptgnf4nnepk10sutqg0msiv1.apps.googleusercontent.com
    SPANNER_DB: projects/luci-tree-status-dev/instances/dev/databases/luci-tree-status-dev

handlers:
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -frontend-client-id ${OAUTH_CLIENT_ID}
  -spanner-database ${SPANNER_DB}
