// Copyright 2017 The LUCI Authors. All rights reserved.
// Use of this source code is governed under the Apache License, Version 2.0
// that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: go.chromium.org/luci/vpython/api/vpython/pep425.proto

package vpython

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a Python PEP425 tag.
type PEP425Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Python is the PEP425 python tag (e.g., "cp27").
	Python string `protobuf:"bytes,1,opt,name=python,proto3" json:"python,omitempty"`
	// ABI is the PEP425 "python ABI" tag (e.g., "cp27mu", "none").
	Abi string `protobuf:"bytes,2,opt,name=abi,proto3" json:"abi,omitempty"`
	// Platform is the PEP425 "python platform" tag (e.g., "linux_x86_64",
	// "armv7l", "any").
	Platform string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
}

func (x *PEP425Tag) Reset() {
	*x = PEP425Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PEP425Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEP425Tag) ProtoMessage() {}

func (x *PEP425Tag) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEP425Tag.ProtoReflect.Descriptor instead.
func (*PEP425Tag) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDescGZIP(), []int{0}
}

func (x *PEP425Tag) GetPython() string {
	if x != nil {
		return x.Python
	}
	return ""
}

func (x *PEP425Tag) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *PEP425Tag) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_go_chromium_org_luci_vpython_api_vpython_pep425_proto protoreflect.FileDescriptor

var file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDesc = []byte{
	0x0a, 0x35, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x6c, 0x75, 0x63, 0x69, 0x2f, 0x76, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x2f, 0x70, 0x65, 0x70, 0x34, 0x32,
	0x35, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x76, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e,
	0x22, 0x51, 0x0a, 0x09, 0x50, 0x45, 0x50, 0x34, 0x32, 0x35, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x79, 0x74, 0x68, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x62, 0x69, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x62, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x6c, 0x75, 0x63, 0x69, 0x2f, 0x76, 0x70, 0x79, 0x74,
	0x68, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDescOnce sync.Once
	file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDescData = file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDesc
)

func file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDescGZIP() []byte {
	file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDescOnce.Do(func() {
		file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDescData)
	})
	return file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDescData
}

var file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_goTypes = []any{
	(*PEP425Tag)(nil), // 0: vpython.PEP425Tag
}
var file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_init() }
func file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_init() {
	if File_go_chromium_org_luci_vpython_api_vpython_pep425_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PEP425Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_goTypes,
		DependencyIndexes: file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_depIdxs,
		MessageInfos:      file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_msgTypes,
	}.Build()
	File_go_chromium_org_luci_vpython_api_vpython_pep425_proto = out.File
	file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_rawDesc = nil
	file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_goTypes = nil
	file_go_chromium_org_luci_vpython_api_vpython_pep425_proto_depIdxs = nil
}
