// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go.chromium.org/luci/common/proto/milo/manifest_diff.proto

package milo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gitiles1 "go.chromium.org/luci/common/proto/gitiles"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Stat indicates how a given item has changed.
type ManifestDiff_Stat int32

const (
	// These two items are identical
	ManifestDiff_EQUAL ManifestDiff_Stat = 0
	// The item was added in `new` compared to `old`
	ManifestDiff_ADDED ManifestDiff_Stat = 1
	// The item was removed in `new` compared to `old`
	ManifestDiff_REMOVED ManifestDiff_Stat = 2
	// The item is in both, but is incomparable (e.g. repo_url changed from
	// `old` to `new`).
	ManifestDiff_MODIFIED ManifestDiff_Stat = 4
	// The item is in both, and is directly comparable (e.g. different
	// revisions of the same repo_url). This only applies to SCM messages.
	//
	// This is 0x8 | MODIFIED, so that users who don't care about DIFF v.
	// MODIFIED can check `Status & MODIFIED`.
	ManifestDiff_DIFF ManifestDiff_Stat = 12
)

var ManifestDiff_Stat_name = map[int32]string{
	0:  "EQUAL",
	1:  "ADDED",
	2:  "REMOVED",
	4:  "MODIFIED",
	12: "DIFF",
}
var ManifestDiff_Stat_value = map[string]int32{
	"EQUAL":    0,
	"ADDED":    1,
	"REMOVED":  2,
	"MODIFIED": 4,
	"DIFF":     12,
}

func (x ManifestDiff_Stat) String() string {
	return proto.EnumName(ManifestDiff_Stat_name, int32(x))
}
func (ManifestDiff_Stat) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0} }

// ManifestDiff holds basic difference information between two source manifests.
type ManifestDiff struct {
	// The older of the two manifests.
	Old *Manifest `protobuf:"bytes,1,opt,name=old" json:"old,omitempty"`
	// The newer of the two manifests.
	New *Manifest `protobuf:"bytes,2,opt,name=new" json:"new,omitempty"`
	// This indicates if there is some overall difference between old and new.
	Overall     ManifestDiff_Stat                  `protobuf:"varint,3,opt,name=overall,enum=milo.ManifestDiff_Stat" json:"overall,omitempty"`
	Directories map[string]*ManifestDiff_Directory `protobuf:"bytes,4,rep,name=directories" json:"directories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ManifestDiff) Reset()                    { *m = ManifestDiff{} }
func (m *ManifestDiff) String() string            { return proto.CompactTextString(m) }
func (*ManifestDiff) ProtoMessage()               {}
func (*ManifestDiff) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ManifestDiff) GetOld() *Manifest {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *ManifestDiff) GetNew() *Manifest {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *ManifestDiff) GetOverall() ManifestDiff_Stat {
	if m != nil {
		return m.Overall
	}
	return ManifestDiff_EQUAL
}

func (m *ManifestDiff) GetDirectories() map[string]*ManifestDiff_Directory {
	if m != nil {
		return m.Directories
	}
	return nil
}

type ManifestDiff_GitCheckout struct {
	// Note: if this is DIFF, it is sensible to compute
	//   `git log git_canonical_url old.revision new.revision`
	Overall ManifestDiff_Stat `protobuf:"varint,1,opt,name=overall,enum=milo.ManifestDiff_Stat" json:"overall,omitempty"`
	// This URL should be used for RPCs. It may differ from the url in old or
	// new if the service computing this ManifestDiff knows of e.g. a repo URL
	// migration.
	RepoUrl string `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl" json:"repo_url,omitempty"`
	// If git_checkout==DIFF, and your request included history, this will be
	// populated with GitCommits.
	History []*gitiles1.LogCommit `protobuf:"bytes,3,rep,name=history" json:"history,omitempty"`
}

func (m *ManifestDiff_GitCheckout) Reset()                    { *m = ManifestDiff_GitCheckout{} }
func (m *ManifestDiff_GitCheckout) String() string            { return proto.CompactTextString(m) }
func (*ManifestDiff_GitCheckout) ProtoMessage()               {}
func (*ManifestDiff_GitCheckout) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0} }

func (m *ManifestDiff_GitCheckout) GetOverall() ManifestDiff_Stat {
	if m != nil {
		return m.Overall
	}
	return ManifestDiff_EQUAL
}

func (m *ManifestDiff_GitCheckout) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

func (m *ManifestDiff_GitCheckout) GetHistory() []*gitiles1.LogCommit {
	if m != nil {
		return m.History
	}
	return nil
}

type ManifestDiff_Directory struct {
	// This is the overall status for this Directory.
	Overall        ManifestDiff_Stat         `protobuf:"varint,1,opt,name=overall,enum=milo.ManifestDiff_Stat" json:"overall,omitempty"`
	GitCheckout    *ManifestDiff_GitCheckout `protobuf:"bytes,2,opt,name=git_checkout,json=gitCheckout" json:"git_checkout,omitempty"`
	CipdServerHost ManifestDiff_Stat         `protobuf:"varint,3,opt,name=cipd_server_host,json=cipdServerHost,enum=milo.ManifestDiff_Stat" json:"cipd_server_host,omitempty"`
	// Note: this will only ever be MODIFIED, because we cannot (yet) determine
	// if two versions of a cipd package are diffable. We may later implement
	// DIFF detection (i.e. if both packages use `version:<sha1>` tags).
	CipdPackage        map[string]ManifestDiff_Stat `protobuf:"bytes,4,rep,name=cipd_package,json=cipdPackage" json:"cipd_package,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=milo.ManifestDiff_Stat"`
	IsolatedServerHost ManifestDiff_Stat            `protobuf:"varint,5,opt,name=isolated_server_host,json=isolatedServerHost,enum=milo.ManifestDiff_Stat" json:"isolated_server_host,omitempty"`
	// This merely indicates if the list of isolated hashes was the same or not;
	// there's not a good way to register the two lists.
	//
	// Since order-of-application for isolateds matters, this will indicate
	// MODIFIED if the order of isolated hashes changes.
	Isolated ManifestDiff_Stat `protobuf:"varint,6,opt,name=isolated,enum=milo.ManifestDiff_Stat" json:"isolated,omitempty"`
}

func (m *ManifestDiff_Directory) Reset()                    { *m = ManifestDiff_Directory{} }
func (m *ManifestDiff_Directory) String() string            { return proto.CompactTextString(m) }
func (*ManifestDiff_Directory) ProtoMessage()               {}
func (*ManifestDiff_Directory) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 1} }

func (m *ManifestDiff_Directory) GetOverall() ManifestDiff_Stat {
	if m != nil {
		return m.Overall
	}
	return ManifestDiff_EQUAL
}

func (m *ManifestDiff_Directory) GetGitCheckout() *ManifestDiff_GitCheckout {
	if m != nil {
		return m.GitCheckout
	}
	return nil
}

func (m *ManifestDiff_Directory) GetCipdServerHost() ManifestDiff_Stat {
	if m != nil {
		return m.CipdServerHost
	}
	return ManifestDiff_EQUAL
}

func (m *ManifestDiff_Directory) GetCipdPackage() map[string]ManifestDiff_Stat {
	if m != nil {
		return m.CipdPackage
	}
	return nil
}

func (m *ManifestDiff_Directory) GetIsolatedServerHost() ManifestDiff_Stat {
	if m != nil {
		return m.IsolatedServerHost
	}
	return ManifestDiff_EQUAL
}

func (m *ManifestDiff_Directory) GetIsolated() ManifestDiff_Stat {
	if m != nil {
		return m.Isolated
	}
	return ManifestDiff_EQUAL
}

func init() {
	proto.RegisterType((*ManifestDiff)(nil), "milo.ManifestDiff")
	proto.RegisterType((*ManifestDiff_GitCheckout)(nil), "milo.ManifestDiff.GitCheckout")
	proto.RegisterType((*ManifestDiff_Directory)(nil), "milo.ManifestDiff.Directory")
	proto.RegisterEnum("milo.ManifestDiff_Stat", ManifestDiff_Stat_name, ManifestDiff_Stat_value)
}

func init() {
	proto.RegisterFile("go.chromium.org/luci/common/proto/milo/manifest_diff.proto", fileDescriptor2)
}

var fileDescriptor2 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xd1, 0x8a, 0xda, 0x40,
	0x14, 0x6d, 0x36, 0xba, 0xea, 0x8d, 0x48, 0x18, 0x0a, 0x4d, 0x43, 0x29, 0xb2, 0x7d, 0xf1, 0xa1,
	0x9b, 0x50, 0xa5, 0x50, 0xf6, 0x4d, 0x4c, 0x6c, 0x85, 0x95, 0xdd, 0x66, 0xd9, 0xf6, 0xa5, 0x20,
	0x69, 0x1c, 0xe3, 0xe0, 0xc4, 0x2b, 0x93, 0xd1, 0xc5, 0x4f, 0xe8, 0xb7, 0xf6, 0xa1, 0xbf, 0x50,
	0x26, 0x26, 0xdd, 0xec, 0x22, 0xd9, 0xb6, 0x6f, 0xe3, 0xbd, 0xe7, 0x9c, 0x7b, 0xee, 0x3d, 0x06,
	0x2e, 0x62, 0x74, 0xa2, 0xa5, 0xc0, 0x84, 0x6d, 0x13, 0x07, 0x45, 0xec, 0xf2, 0x6d, 0xc4, 0xdc,
	0x08, 0x93, 0x04, 0xd7, 0xee, 0x46, 0xa0, 0x44, 0x37, 0x61, 0x1c, 0xdd, 0x24, 0x5c, 0xb3, 0x05,
	0x4d, 0xe5, 0x6c, 0xce, 0x16, 0x0b, 0x27, 0x6b, 0x90, 0x9a, 0xea, 0xd8, 0x83, 0xa7, 0x15, 0x62,
	0x26, 0x19, 0xa7, 0xa9, 0xcb, 0x31, 0x3e, 0x50, 0xed, 0xf7, 0xff, 0x38, 0xf6, 0x40, 0x3b, 0xfb,
	0xd9, 0x80, 0xf6, 0x34, 0x2f, 0x79, 0x6c, 0xb1, 0x20, 0x5d, 0xd0, 0x91, 0xcf, 0x2d, 0xad, 0xab,
	0xf5, 0x8c, 0x7e, 0xc7, 0x51, 0x1c, 0xa7, 0x00, 0x04, 0xaa, 0xa5, 0x10, 0x6b, 0x7a, 0x67, 0x9d,
	0x1c, 0x47, 0xac, 0xe9, 0x1d, 0x79, 0x07, 0x0d, 0xdc, 0x51, 0x11, 0x72, 0x6e, 0xe9, 0x5d, 0xad,
	0xd7, 0xe9, 0xbf, 0x78, 0x88, 0x52, 0x83, 0x9c, 0x1b, 0x19, 0xca, 0xa0, 0xc0, 0x11, 0x1f, 0x8c,
	0x39, 0x13, 0x34, 0x92, 0x28, 0x18, 0x4d, 0xad, 0x5a, 0x57, 0xef, 0x19, 0xfd, 0x37, 0x47, 0x68,
	0xde, 0x3d, 0xca, 0x5f, 0x4b, 0xb1, 0x0f, 0xca, 0x3c, 0xfb, 0x87, 0x06, 0xc6, 0x47, 0x26, 0x47,
	0x4b, 0x1a, 0xad, 0x70, 0x2b, 0xcb, 0x4e, 0xb4, 0xbf, 0x74, 0xf2, 0x12, 0x9a, 0x82, 0x6e, 0x70,
	0xb6, 0x15, 0x3c, 0xdb, 0xb1, 0x15, 0x34, 0xd4, 0xef, 0x5b, 0xc1, 0xc9, 0x5b, 0x68, 0x2c, 0x59,
	0x2a, 0x51, 0xec, 0x2d, 0x3d, 0x33, 0x48, 0x9c, 0x3c, 0x08, 0xe7, 0x12, 0xe3, 0x11, 0x26, 0x09,
	0x93, 0x41, 0x01, 0xb1, 0x7f, 0xe9, 0xd0, 0x2a, 0xdc, 0xee, 0xff, 0xc7, 0xc9, 0x10, 0xda, 0x31,
	0x93, 0xb3, 0x28, 0x5f, 0x26, 0xbf, 0xf8, 0xeb, 0x23, 0xbc, 0xd2, 0xca, 0x81, 0x11, 0x97, 0xf6,
	0x1f, 0x82, 0x19, 0xb1, 0xcd, 0x7c, 0x96, 0x52, 0xb1, 0xa3, 0x62, 0xb6, 0xc4, 0x54, 0x3e, 0x15,
	0x49, 0x47, 0x11, 0x6e, 0x32, 0xfc, 0x27, 0x4c, 0x25, 0xb9, 0x86, 0x76, 0x26, 0xb1, 0x09, 0xa3,
	0x55, 0x18, 0xd3, 0x3c, 0x9a, 0xf3, 0x8a, 0x68, 0xf6, 0xce, 0x88, 0x6d, 0xe6, 0xd7, 0x07, 0x7c,
	0x1e, 0x52, 0x74, 0x5f, 0x21, 0x13, 0x78, 0xce, 0x52, 0xe4, 0xa1, 0xa4, 0x0f, 0x8d, 0xd5, 0xab,
	0x8d, 0x91, 0x82, 0x54, 0x32, 0x37, 0x80, 0x66, 0x51, 0xb5, 0x4e, 0xab, 0xe9, 0x7f, 0x80, 0xf6,
	0x57, 0x30, 0x1f, 0x1b, 0x24, 0x26, 0xe8, 0x2b, 0xba, 0xcf, 0xa2, 0x69, 0x05, 0xea, 0x49, 0xce,
	0xa1, 0xbe, 0x0b, 0xf9, 0x96, 0x66, 0x67, 0xaf, 0xd0, 0x3d, 0xa0, 0x2e, 0x4e, 0x3e, 0x68, 0xf6,
	0x37, 0x30, 0x1f, 0xff, 0x3d, 0x8f, 0x08, 0xf7, 0xcb, 0xc2, 0x46, 0xff, 0x55, 0xd5, 0x25, 0x4b,
	0xea, 0x67, 0x43, 0xa8, 0xa9, 0x81, 0xa4, 0x05, 0x75, 0xff, 0xf3, 0xed, 0xf0, 0xd2, 0x7c, 0xa6,
	0x9e, 0x43, 0xcf, 0xf3, 0x3d, 0x53, 0x23, 0x06, 0x34, 0x02, 0x7f, 0x7a, 0xf5, 0xc5, 0xf7, 0xcc,
	0x13, 0xd2, 0x86, 0xe6, 0xf4, 0xca, 0x9b, 0x8c, 0x27, 0xbe, 0x67, 0xd6, 0x48, 0x13, 0x6a, 0xde,
	0x64, 0x3c, 0x36, 0xdb, 0xdf, 0x4f, 0xb3, 0x8f, 0x7e, 0xf0, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd4,
	0xb3, 0x7e, 0x63, 0xa4, 0x04, 0x00, 0x00,
}
