service: default
runtime: go111

instance_class: F4_1G

automatic_scaling:
  min_idle_instances: 10
  max_idle_instances: automatic  # default value
  min_pending_latency: 10ms
  max_pending_latency: 30ms  # default value
  max_concurrent_requests: 8  # note: the default value is 10

handlers:
# Single robots.txt file, must be served under root.
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Static resources such as css and js files.
- url: /static
  secure: always
  static_dir: static

# All internal handlers, such as cron.
- url: /internal/.*
  script: auto
  secure: always
  login: admin

# Pubsub Handler.  This is strictly necessary because the default module
# contains a /.* routing rule, so if it was targeted directly, we still want
# login:admin to apply.
- url: /_ah/push-handlers/.*
  script: auto
  secure: always
  login: admin

# ResultUI frontend routes.
- url: /ui/(login|(inv|p|b|artifact)/.*)
  secure: always
  static_files: resultui/index.html
  upload: resultui/index.html
  # The resources are cached by the service worker. Don't serve the old content
  # when the service worker tries to fetch a new version.
  expiration: 0s

# Immutable ResultUI static resources.
- url: /ui/immutable
  secure: always
  static_dir: resultui/immutable
  # All files have content hash in their filenames.
  # So they can be cached longer.
  expiration: 7d

# Host root-sw.js at root so it can have root scope.
- url: /(root-sw\.js(\.map)?)$
  secure: always
  static_files: resultui/\1
  upload: resultui/root-sw\.js(\.map)?$

# Other ResultUI static resources.
- url: /ui
  secure: always
  static_dir: resultui
  # The resources are cached by the service worker. Don't serve the old content
  # when the service worker tries to fetch a new version.
  expiration: 0s

# The rest is handled by Go code.
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup
