// Code generated by "stringer -type=Toggle"; DO NOT EDIT.

package datastore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Auto-0]
	_ = x[On-1]
	_ = x[Off-2]
}

const _Toggle_name = "AutoOnOff"

var _Toggle_index = [...]uint8{0, 4, 6, 9}

func (i Toggle) String() string {
	if i >= Toggle(len(_Toggle_index)-1) {
		return "Toggle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Toggle_name[_Toggle_index[i]:_Toggle_index[i+1]]
}
