service: default
runtime: go123

instance_class: F4

automatic_scaling:
  max_concurrent_requests: 80

# luci_gae_vars is interpreted by gae.py, for apps deployed manually.
# It maps the app ID being deployed to values of vars used below.
luci_gae_vars:
  luci-change-verifier-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    FRONTEND_CLIENT_ID: 880120143479-shb008ruk2kms1178b14nhgjr47o4emm.apps.googleusercontent.com
    CONFIG_SERVICE_HOST: config.luci.app
    LUCI_TREE_STATUS_HOST: staging.treestatus.api.luci.app
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
    VPC_CONNECTOR: projects/luci-change-verifier-dev/locations/us-central1/connectors/connector
    REDIS_ADDR: 10.42.70.59:6379
    DS_CACHE: redis
    OAUTH_CLIENT_ID: 339503751427-hcq50e5kdrfsokum5gh8l459h8p0n92q.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://luci-change-verifier-dev.appspot.com/auth/openid/callback
    ROOT_SECRET: sm://root-secret
    TINK_AEAD_KEY: sm://tink-aead-primary
    ANALYTICS_ID: G-YP2P6PXQDT

vpc_access_connector:
  name: ${VPC_CONNECTOR}

handlers:
- url: /static/bootstrap
  static_dir: static/bootstrap
  secure: always
- url: /static/jquery
  static_dir: static/jquery
  secure: always
- url: /static/images
  static_dir: static/images
  secure: always
- url: /.*
  script: auto
  secure: always

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -frontend-client-id ${FRONTEND_CLIENT_ID}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -ts-mon-account ${TS_MON_ACCOUNT}
  -redis-addr ${REDIS_ADDR}
  -ds-cache ${DS_CACHE}
  -cloud-error-reporting
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -encrypted-cookies-tink-aead-key ${TINK_AEAD_KEY}
  -gerrit-auth-signer-account gerritcodereview@system.gserviceaccount.com
  -gerrit-auth-signer-account git-gerrit@system.gserviceaccount.com
  -gerrit-auth-audience https://api.cr.dev
  -luci-tree-status-host ${LUCI_TREE_STATUS_HOST}
  -root-secret ${ROOT_SECRET}
  -primary-tink-aead-key ${TINK_AEAD_KEY}
  -analytics-id ${ANALYTICS_ID}
  -dsmapper-mapper-queue dsmapper
  -dsmapper-control-queue default
  -ts-mon-flush-interval 1m
  -ts-mon-flush-timeout 55s
