service: default
runtime: go115

instance_class: F4

automatic_scaling:
  max_concurrent_requests: 80
  max_instances: 20

# luci_gae_vars is interpreted by gae.py, for apps deployed manually.
# It maps the app ID being deployed to values of vars used below.
luci_gae_vars:
  luci-change-verifier-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    FRONTEND_CLIENT_ID: 880120143479-shb008ruk2kms1178b14nhgjr47o4emm.apps.googleusercontent.com
    CONFIG_SERVICE_HOST: luci-config.appspot.com
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
    VPC_CONNECTOR: projects/luci-change-verifier-dev/locations/us-central1/connectors/connector
    REDIS_ADDR: 10.71.21.171:6379
    DS_CACHE: redis

vpc_access_connector:
  name: ${VPC_CONNECTOR}

handlers:
- url: /.*
  script: auto
  secure: always

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -frontend-client-id ${FRONTEND_CLIENT_ID}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -ts-mon-account ${TS_MON_ACCOUNT}
  -redis-addr ${REDIS_ADDR}
  -ds-cache ${DS_CACHE}
  -cloud-error-reporting
