service: default
runtime: go124

instance_class: F4

inbound_services:
- warmup

# luci_gae_vars is interpreted by gae.py, for apps deployed manually.
# It maps the app ID being deployed to values of vars used below.
luci_gae_vars:
  luci-token-server-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    CONFIG_SERVICE_HOST: config.luci.app
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
    VPC_CONNECTOR: projects/luci-token-server-dev/locations/us-central1/connectors/connector
    REDIS_ADDR: 10.35.65.123:6379
    DS_CACHE: redis

vpc_access_connector:
  name: ${VPC_CONNECTOR}

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -ts-mon-account ${TS_MON_ACCOUNT}
  -redis-addr ${REDIS_ADDR}
  -ds-cache ${DS_CACHE}
  -cloud-error-reporting
