service: default
runtime: go124

luci_gae_vars:
  luci-deploy-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    OAUTH_CLIENT_ID: 207763751383-omoj7glbfqu8l2n4fhp1o53glb2rl301.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://luci-deploy-dev.appspot.com/auth/openid/callback
    ROOT_SECRET: sm://root-secret
    TINK_AEAD_KEY: sm://tink-aead-primary
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com

instance_class: F4

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -cloud-error-reporting
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -encrypted-cookies-tink-aead-key ${TINK_AEAD_KEY}
  -frontend-client-id ${OAUTH_CLIENT_ID}
  -primary-tink-aead-key ${TINK_AEAD_KEY}
  -root-secret ${ROOT_SECRET}
  -ts-mon-account ${TS_MON_ACCOUNT}
