service: default
runtime: go124

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
luci_gae_vars:
  cr-buildbucket-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    PROFILING_PROBABILITY: "1.0"
    REDIS_ADDR: 10.90.74.59:6379
    VPC_CONNECTOR: projects/cr-buildbucket-dev/locations/us-central1/connectors/connector
    DS_CACHE: redis
    CONFIG_SERVICE_HOST: config.luci.app
    OAUTH_CLIENT_ID: 1037694916935-kf96dqdbptp98pahigutgighdft4s9s9.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://cr-buildbucket-dev.appspot.com/auth/openid/callback
    TURBO_CI_STAGES_SERVICE_ACCOUNT: turbo-ci-stages-qual-jobs@system.gserviceaccount.com
  cr-buildbucket:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
    PROFILING_PROBABILITY: "0.02"
    REDIS_ADDR: 10.52.56.84:6379
    VPC_CONNECTOR: projects/cr-buildbucket/locations/us-central1/connectors/connector-e2-standard-4
    DS_CACHE: redis
    CONFIG_SERVICE_HOST: config.luci.app
    OAUTH_CLIENT_ID: 174799409470-0041crblugt4hrqsdrjatu869a41jdbq.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://cr-buildbucket.appspot.com/auth/openid/callback
    TURBO_CI_STAGES_SERVICE_ACCOUNT: turbo-ci-stages@system.gserviceaccount.com

vpc_access_connector:
  name: ${VPC_CONNECTOR}

automatic_scaling:
  min_idle_instances: 1
  max_concurrent_requests: 80

inbound_services:
- warmup

instance_class: F4

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -bqlog-dataset sandbox
  -ts-mon-account app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
  -cloud-error-reporting
  -profiling-probability ${PROFILING_PROBABILITY}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -gerrit-auth-signer-account gerritcodereview@system.gserviceaccount.com
  -gerrit-auth-signer-account git-gerrit@system.gserviceaccount.com
  -gerrit-auth-audience https://api.cr.dev
  -root-secret sm://root-secret
  -primary-tink-aead-key sm://tink-aead-primary
  -ds-connection-pool-size 8
  -redis-addr ${REDIS_ADDR}
  -ds-cache ${DS_CACHE}
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -turbo-ci-stages-service-account ${TURBO_CI_STAGES_SERVICE_ACCOUNT}

handlers:
- url: /.*
  script: auto
  secure: always
