runtime: go124
instance_class: F4

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/HEAD/examples/appengine/helloworld_v2/app.yaml

# IMPORTANT: Keep in sync with app.star files in
# https://chrome-internal.googlesource.com/infradata/gae/+/refs/heads/main/apps/luci-bisection/
luci_gae_vars:
  luci-bisection-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    CONFIG_SERVICE_HOST: config.luci.app
    CRON_AUTHORIZED_CALLER: cloud-scheduler-jobs@luci-bisection-dev.iam.gserviceaccount.com
    LUCI_ANALYSIS_PROJECT: luci-analysis-dev
    LUCI_ANALYSIS_HOST: staging.analysis.api.luci.app
    LUCI_BISECTION_HOST: staging.bisection.api.luci.app
    PUBSUB_AUTHORIZED_CALLER: cloud-pubsub-pusher@luci-bisection-dev.iam.gserviceaccount.com
    TINK_AEAD_KEY: sm://tink-aead-primary
    TQ_PUSH_AS: cloud-tasks-pusher@luci-bisection-dev.iam.gserviceaccount.com
    TQ_TARGET_HOST: staging.bisection.api.luci.app
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
    UI_REDIRECT_URL: luci-milo-dev.appspot.com/ui/bisection

handlers:
- url: /.*
  script: auto
  secure: always

# Pubsub Handler.
- url: /_ah/push-handlers/.*
  script: auto
  secure: always

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -cron-authorized-caller ${CRON_AUTHORIZED_CALLER}
  -luci-analysis-project ${LUCI_ANALYSIS_PROJECT}
  -luci-analysis-host ${LUCI_ANALYSIS_HOST}
  -luci-bisection-host ${LUCI_BISECTION_HOST}
  -primary-tink-aead-key ${TINK_AEAD_KEY}
  -pubsub-authorized-caller ${PUBSUB_AUTHORIZED_CALLER}
  -tq-default-target-host ${TQ_TARGET_HOST}
  -tq-push-as ${TQ_PUSH_AS}
  -tq-sweep-initiation-launcher ${CRON_AUTHORIZED_CALLER}
  -ts-mon-account ${TS_MON_ACCOUNT}
  -ui-redirect-url ${UI_REDIRECT_URL}
