runtime: go123
service: default
app_engine_apis: true

# luci_gae_vars is interpreted by gae.py, for apps deployed manually.
# It maps the app ID being deployed to values of vars used below.
luci_gae_vars:
  chrome-infra-auth-dev:
    OAUTH_CLIENT_ID: 502071599212-d623foidam4v1pgcjqeala1puafovh1c.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://chrome-infra-auth-dev.appspot.com/auth/openid/callback
    ROOT_SECRET: sm://root-secret
    TINK_AEAD_KEY: sm://tink-aead-primary
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
    CONFIG_SERVICE_HOST: config.luci.app

# Environment variables while transitioning from
# Auth Service v1 (Python) to Auth Service v2 (Go).
env_variables:
  DRY_RUN_API_CHANGES: false
  DRY_RUN_CRON_CONFIG: false
  DRY_RUN_CRON_REALMS: false
  DRY_RUN_CRON_STALE_AUTH: false
  DRY_RUN_TQ_CHANGELOG: false
  DRY_RUN_TQ_REPLICATION: false

inbound_services:
- warmup

handlers:
- url: /ui/static
  static_dir: static
  secure: always
  http_headers:
    Content-Security-Policy: "default-src https: 'self'"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    X-Frame-Options: DENY

- url: /.*
  script: auto
  secure: always

entrypoint: >
  main
  -cloud-error-reporting
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -encrypted-cookies-tink-aead-key ${TINK_AEAD_KEY}
  -frontend-client-id ${OAUTH_CLIENT_ID}
  -root-secret ${ROOT_SECRET}
  -ts-mon-account ${TS_MON_ACCOUNT}
  -config-service-host ${CONFIG_SERVICE_HOST}
