// Copyright 2016 The LUCI Authors. All rights reserved.
// Use of this source code is governed under the Apache License, Version 2.0
// that can be found in the LICENSE file.

package main

import (
	"text/template"

	"github.com/luci/luci-go/grpc/internal/svctool"
)

var (
	tmpl = template.Must(template.New("").Parse(
		`// Code generated by svcdec; DO NOT EDIT

package {{.PackageName}}

import (
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	{{range .ExtraImports}}
	{{.Name}} "{{.Path}}"{{end}}
)

{{range .Services}}
{{$StructName := .StructName}}
type {{$StructName}} struct {
	// Service is the service to decorate.
	Service {{.Service.TypeName}}
	// Prelude is called for each method before forwarding the call to Service.
	// If Prelude returns an error, then the call is skipped and the error is
	// processed via the Postlude (if one is defined), or it is returned directly.
	Prelude func(c context.Context, methodName string, req proto.Message) (context.Context, error)
	// Postlude is called for each method after Service has processed the call, or
	// after the Prelude has returned an error. This takes the the Service's
	// response proto (which may be nil) and/or any error. The decorated
	// service will return the response (possibly mutated) and error that Postlude
	// returns.
	Postlude func(c context.Context, methodName string, rsp proto.Message, err error) error
}

{{range .Methods}}
func (s *{{$StructName}}) {{.Name}}(c context.Context, req {{.InputType}}) (rsp {{.OutputType}}, err error) {
	var newCtx context.Context
	if s.Prelude != nil {
		newCtx, err = s.Prelude(c, "{{.Name}}", req)
	}
	if err == nil {
		c = newCtx
		rsp, err = s.Service.{{.Name}}(c, req)
	}
	if s.Postlude != nil {
		err = s.Postlude(c, "{{.Name}}", rsp, err)
	}
	return
}
{{end}}
{{end}}
`))
)

type (
	templateArgs struct {
		PackageName  string
		Services     []*service
		ExtraImports []svctool.Import
	}

	service struct {
		*svctool.Service
		StructName string
	}
)
