runtime: go124

# This is needed to use GAE Mail API via `mailer` module.
app_engine_apis: true

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
luci_gae_vars:
  example-app-id-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    ANALYTICS_ID: G-D45KW5Q1CE
  example-app-id-prod:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
    ANALYTICS_ID: G-B1PDME7S99

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup

entrypoint: >
  main -auth-service-host ${AUTH_SERVICE_HOST} -analytics-id ${ANALYTICS_ID}
