// Copyright 2024 The LUCI Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: go.chromium.org/luci/cv/internal/retention/tasks.proto

package retention

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WipeoutRunsTask wipes out given Runs and its descendent entities that
// are out of the retention policy.
//
// Queue: "data-retention".
type WipeoutRunsTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WipeoutRunsTask) Reset() {
	*x = WipeoutRunsTask{}
	mi := &file_go_chromium_org_luci_cv_internal_retention_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WipeoutRunsTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WipeoutRunsTask) ProtoMessage() {}

func (x *WipeoutRunsTask) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_luci_cv_internal_retention_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WipeoutRunsTask.ProtoReflect.Descriptor instead.
func (*WipeoutRunsTask) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *WipeoutRunsTask) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// WipeoutCLsTask wipes out given CLs that are out of the retention policy.
//
// Queue: "data-retention".
type WipeoutCLsTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WipeoutCLsTask) Reset() {
	*x = WipeoutCLsTask{}
	mi := &file_go_chromium_org_luci_cv_internal_retention_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WipeoutCLsTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WipeoutCLsTask) ProtoMessage() {}

func (x *WipeoutCLsTask) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_luci_cv_internal_retention_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WipeoutCLsTask.ProtoReflect.Descriptor instead.
func (*WipeoutCLsTask) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *WipeoutCLsTask) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// WipeoutTryjobsTask wipes out given tryjobs that are out of the retention
// policy.
//
// Queue: "data-retention".
type WipeoutTryjobsTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WipeoutTryjobsTask) Reset() {
	*x = WipeoutTryjobsTask{}
	mi := &file_go_chromium_org_luci_cv_internal_retention_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WipeoutTryjobsTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WipeoutTryjobsTask) ProtoMessage() {}

func (x *WipeoutTryjobsTask) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_luci_cv_internal_retention_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WipeoutTryjobsTask.ProtoReflect.Descriptor instead.
func (*WipeoutTryjobsTask) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *WipeoutTryjobsTask) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_go_chromium_org_luci_cv_internal_retention_tasks_proto protoreflect.FileDescriptor

const file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDesc = "" +
	"\n" +
	"6go.chromium.org/luci/cv/internal/retention/tasks.proto\x12\x15cv.internal.retention\"#\n" +
	"\x0fWipeoutRunsTask\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\"\n" +
	"\x0eWipeoutCLsTask\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"&\n" +
	"\x12WipeoutTryjobsTask\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03idsB6Z4go.chromium.org/luci/cv/internal/retention;retentionb\x06proto3"

var (
	file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescOnce sync.Once
	file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescData []byte
)

func file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescGZIP() []byte {
	file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescOnce.Do(func() {
		file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDesc), len(file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDesc)))
	})
	return file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDescData
}

var file_go_chromium_org_luci_cv_internal_retention_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_go_chromium_org_luci_cv_internal_retention_tasks_proto_goTypes = []any{
	(*WipeoutRunsTask)(nil),    // 0: cv.internal.retention.WipeoutRunsTask
	(*WipeoutCLsTask)(nil),     // 1: cv.internal.retention.WipeoutCLsTask
	(*WipeoutTryjobsTask)(nil), // 2: cv.internal.retention.WipeoutTryjobsTask
}
var file_go_chromium_org_luci_cv_internal_retention_tasks_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_chromium_org_luci_cv_internal_retention_tasks_proto_init() }
func file_go_chromium_org_luci_cv_internal_retention_tasks_proto_init() {
	if File_go_chromium_org_luci_cv_internal_retention_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDesc), len(file_go_chromium_org_luci_cv_internal_retention_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_chromium_org_luci_cv_internal_retention_tasks_proto_goTypes,
		DependencyIndexes: file_go_chromium_org_luci_cv_internal_retention_tasks_proto_depIdxs,
		MessageInfos:      file_go_chromium_org_luci_cv_internal_retention_tasks_proto_msgTypes,
	}.Build()
	File_go_chromium_org_luci_cv_internal_retention_tasks_proto = out.File
	file_go_chromium_org_luci_cv_internal_retention_tasks_proto_goTypes = nil
	file_go_chromium_org_luci_cv_internal_retention_tasks_proto_depIdxs = nil
}
