// Code generated by svcdec; DO NOT EDIT.

package analysispb

import (
	"context"

	proto "github.com/golang/protobuf/proto"
)

type DecoratedChangepoints struct {
	// Service is the service to decorate.
	Service ChangepointsServer
	// Prelude is called for each method before forwarding the call to Service.
	// If Prelude returns an error, then the call is skipped and the error is
	// processed via the Postlude (if one is defined), or it is returned directly.
	Prelude func(ctx context.Context, methodName string, req proto.Message) (context.Context, error)
	// Postlude is called for each method after Service has processed the call, or
	// after the Prelude has returned an error. This takes the Service's
	// response proto (which may be nil) and/or any error. The decorated
	// service will return the response (possibly mutated) and error that Postlude
	// returns.
	Postlude func(ctx context.Context, methodName string, rsp proto.Message, err error) error
}

func (s *DecoratedChangepoints) QueryChangepointGroupSummaries(ctx context.Context, req *QueryChangepointGroupSummariesRequestLegacy) (rsp *QueryChangepointGroupSummariesResponseLegacy, err error) {
	if s.Prelude != nil {
		var newCtx context.Context
		newCtx, err = s.Prelude(ctx, "QueryChangepointGroupSummaries", req)
		if err == nil {
			ctx = newCtx
		}
	}
	if err == nil {
		rsp, err = s.Service.QueryChangepointGroupSummaries(ctx, req)
	}
	if s.Postlude != nil {
		err = s.Postlude(ctx, "QueryChangepointGroupSummaries", rsp, err)
	}
	return
}

func (s *DecoratedChangepoints) QueryGroupSummaries(ctx context.Context, req *QueryChangepointGroupSummariesRequest) (rsp *QueryChangepointGroupSummariesResponse, err error) {
	if s.Prelude != nil {
		var newCtx context.Context
		newCtx, err = s.Prelude(ctx, "QueryGroupSummaries", req)
		if err == nil {
			ctx = newCtx
		}
	}
	if err == nil {
		rsp, err = s.Service.QueryGroupSummaries(ctx, req)
	}
	if s.Postlude != nil {
		err = s.Postlude(ctx, "QueryGroupSummaries", rsp, err)
	}
	return
}

func (s *DecoratedChangepoints) QueryChangepointsInGroup(ctx context.Context, req *QueryChangepointsInGroupRequest) (rsp *QueryChangepointsInGroupResponse, err error) {
	if s.Prelude != nil {
		var newCtx context.Context
		newCtx, err = s.Prelude(ctx, "QueryChangepointsInGroup", req)
		if err == nil {
			ctx = newCtx
		}
	}
	if err == nil {
		rsp, err = s.Service.QueryChangepointsInGroup(ctx, req)
	}
	if s.Postlude != nil {
		err = s.Postlude(ctx, "QueryChangepointsInGroup", rsp, err)
	}
	return
}
