service: default
runtime: go123
app_engine_apis: true

instance_class: F4
automatic_scaling:
  max_concurrent_requests: 20
  min_idle_instances: 1

handlers:
- url: /(internal|admin)/.*
  script: auto
  secure: always
  login: admin

- url: /.*
  script: auto
  secure: always
