runtime: go124

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
luci_gae_vars:
  cas-viewer-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com

entrypoint: >
  main -auth-service-host ${AUTH_SERVICE_HOST}

handlers:
  - url: /static
    static_dir: static
